steps:

# Desencriptar el plan terraform
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=/workspace/tf_plan.enc
  - --plaintext-file=/workspace/tf_plan.bin
  - --location=global
  - --keyring=cloudbuild-secrets
  - --key=cloudbuild-key

# Ejecutar el plan Terraform
- name: gcr.io/$PROJECT_ID/terraform
  entrypoint: 'bash'
  dir: '/workspace/terraform'
  args:
  - '-c'
  - |
    terraform init 
    terraform apply /workspace/tf_plan.bin

timeout: 20m
